version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgresGo
    environment:
      POSTGRES_DB: social_media
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1329Pathrapol!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - web_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminGo
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - web_network
  
  apiGolang: 
    depends_on:
      - postgres
    image: chitter_api:1.0
    build: social_media_API/
    restart: always 
    networks:
      - web_network
    ports:
      - "7890:8080"

volumes:
  postgres_data:

networks:
  web_network:
    name: tamnetwork
